### ISSUE TITLE
Remove Spammy SEO language

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/wexfordchiropractic#3]
Language that doesn't make grammatical sense or feels like keyword stuff, such as:

> If you are looking for help with weight management in the Wexford, Gibsonia, Pittsburgh, Pine or Marshall Townships area please call the Wexford Chiropractic Centre at 724-935-1610

Tighten up the language and/or remove.

**Comment by frostyweather** [comment]
Normalized language on all pages and made language more readable for a human.
