### ISSUE TITLE
Add Conditions Intro Paragraph

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/wexfordchiropractic#4]
http://wexfordchiropractic.com/conditions.html

Needs an intro paragraph saying something like "Here are some of the conditions chiropractic care can help with"

**Comment by frostyweather** [comment]
I wrote an intro paragraph and added it [here](http://wexfordchiropractic.com/conditions.html).
Here's what it says:

> Wexford Chiropractic Centre helps to relieve pain and discomfort from the following issues:
